name: "Test"

on: [push, pull_request]

jobs:

  server:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - run: |
        sudo apt-get update
        sudo apt-get -y install libxml2-dev libxmlsec1-dev libxmlsec1-openssl libexempi-dev

    - run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r dev-requirements.txt

  client:

    strategy:
      matrix:
        node-version: ['14.x', '16.x']

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install

    - run: npm run build
  
  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: docker compose build
